### ISSUE TITLE
Mapping over PairRDD using Tuple2 results in GHC bug - makeStatic

### ISSUE THREAD

**Issue by dzhus** [tweag/sparkle#119]
When trying to map a function that swaps `Tuple2` members over a `PairRDD a b` to get `PairRDD b a`, I'm seeing this:

```
$ stack --nix build && stack --nix exec -- sparkle package sparkle-example-rddops && stack --nix exec -- spark-submit --master 'local[1]' sparkle-example-rddops.jar

...

["The","quick","brown","fox","jumps","over","the","lazy","dog"]
"dog lazy the over jumps fox brown quick The"
["ehT","kciuq","nworb","xof","spmuj","revo","eht","yzal","god"]
["The","quick","brown"]
["fox","The","jumps","quick","lazy","dog","over","brown","the"]
True
sparkle-worker: GHC bug - makeStatic: Unresolved static form at line 107, column 1.
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/StaticPtr/Internal.hs:26:5 in base:GHC.StaticPtr.Internal
$ uname -a
Linux osboxes 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
``` 

Here's a minimal example: https://github.com/MailOnline/sparkle/commit/4191d4fd9aa8e020716a709a37f35dc2a907a4bb

If I add `StaticPointers` pragma to `PairRDD` module, it works as expected (https://github.com/MailOnline/sparkle/commit/6708a2a92135481d47cb409c571699374884bfd5). Any ideas as to what is exactly happening here? Is this a combination of https://ghc.haskell.org/trac/ghc/ticket/14204 + `withStatic` in `PairRDD`?

**Comment by mboes** [comment]
Yes, that's right. I got hit myself by this earlier last week. If you'd like to push your change as a PR, I can cut a new point release pronto. Thanks for the bug report!

FWIW, GHC 8.4 should have much better diagnostics.

**Comment by mboes** [comment]
I should clarify - in my case it was a missing `LANGUAGE` pragma in `Language.Java` (now fixed). It's unclear why this is showing up now though, seeing as these `LANGUAGE` pragmas must have been missing for a long time. Might be due to a new compiler version. There might be a few more of these lurking around, since the GHC bug you mention turns what ought to be a compile time error into a runtime error.

**Comment by dzhus** [comment]
Thanks, I opened a PR. There's no rush – I'm fine using Git version, plus I have many more changes coming.
