### ISSUE TITLE
Can't use stack --nix to build in Ubuntu

### ISSUE THREAD

**Issue by JulianZhang** [tweag/sparkle#13]
When I run the build command in Ubuntu, It sad can't find git in nix-path.

I had run the nix-env --install git, but the problem don't fixed.

stack --nix build
Executable named git not found on path: ["/nix/store/y04m80hxjmmyc304rjk09kq4s7ry8n7j-apache-maven-3.3.9/bin","/nix/store/7z8295fdyxnkg3jkp0r7rf1kkqj54i7i-openjdk-8u76b00/bin","/nix/store/i5mb0m7gvfcl4zghfjyxyx3fbzyqmg21-openjdk-8u76b00-jre/bin","/nix/store/fhkjh2m0b6a57bcywi0121zppb7bjji8-spark-1.6.0/bin","/nix/store/00p55fh56q0rj05wa2x0w4r7flr20qwy-zip-3.0/bin","/nix/store/69h2gv9dxhazhy9cg198lsvfi9r1gi9x-ghc-7.10.3/bin","/nix/store/bq65nnhs7gjwdblibg0l89n7qx36mxmw-pkg-config-0.29/bin","/nix/store/l15rppxw3fjyysslj160q31jc7pkqb32-patchelf-0.8/bin","/nix/store/5kicd5g9w5fnn10zv6v3f3j63g2r4c72-paxctl-0.9/bin","/nix/store/bkllwvss62hch8vgxacnpdnvmlldwfxn-gcc-wrapper-4.9.3/bin","/nix/store/9s9r019176g7cvn2nvcw41gsp862y6b4-coreutils-8.24/bin","/nix/store/6hrcxzwk3padb28i3phnmmz15bjjqaj3-findutils-4.4.2/bin","/nix/store/5pa28il3q8v61zvfx1v3kwgw9g6alv1x-diffutils-3.3/bin","/nix/store/a8md7hpm9drjmdhgla0l3pf7llwdkm31-gnused-4.2.2/bin","/nix/store/dy92hq6ryvaj5bx5c6gi6fvnhyxdh78x-gnugrep-2.22/bin","/nix/store/sfccmsc4fwk11w7blz3g0q2hzi9va8f7-gawk-4.1.3/bin","/nix/store/q26acv90dg3iywdfk2q029ixdr3i19rh-gnutar-1.28/bin","/nix/store/xgz5hs1cvlx4vn98qizpqp8x5gwplqks-gzip-1.6/bin","/nix/store/icv8p8zxwdr6ljxb89vyxrmma7h2iqlh-bzip2-1.0.6/bin","/nix/store/n01xbf2w6x5bvxznmllpz60vx5ylpgjj-gnumake-4.1/bin","/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin","/nix/store/fgqamjbhxx6d62myqnp62i7b0bka2yiq-patch-2.7.5/bin","/nix/store/dkwhsgc5qa52hbpn3pg9zzz4kqsclzv0-xz-5.2.2/bin","/nix/store/5idnvskkm4hky2fj335xfbqpfim3g9pd-gcc-4.9.3/bin","/nix/store/iyw7cmmg2yi5cwc1pswfm0wrn1ssk1zh-binutils-2.23.1/bin","/nix/store/n2wxp513rr00f6hr2dy0waqahns49dch-glibc-2.21/bin","/nix/store/9s9r019176g7cvn2nvcw41gsp862y6b4-coreutils-8.24/bin"]

**Comment by mboes** [comment]
This happens when distributed-commands hasn't been checked out yet outside of the nix-shell. I've modified shell.nix to include `git` and `openssh`, so this should work no matter the state of your `.stack-work/` now.
