### ISSUE TITLE
Use "stack build"  failed on Ubuntu

### ISSUE THREAD

**Issue by JulianZhang** [tweag/sparkle#14]
$stack build
sparkle-0.1: configure
sparkle-0.1: build
Progress: 0/3
--  While building package sparkle-0.1 using:
      /home/zhangjun/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 build lib:sparkle --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/zhangjun/sparkle/.stack-work/logs/sparkle-0.1.log

    Configuring sparkle-0.1...
    Preprocessing library sparkle-0.1...

    In file included from cbits/bootstrap.c:4:0:

    /home/zhangjun/sparkle/sparkle/cbits/io_tweag_sparkle_Sparkle.h:2:17:
         fatal error: jni.h: No such file or directory
    compilation terminated.
Progress: 1/3

$ more /home/zhangjun/sparkle/.stack-work/logs/sparkle-0.1.log
Configuring sparkle-0.1...
Preprocessing library sparkle-0.1...

In file included from cbits/bootstrap.c:4:0:

cbits/io_tweag_sparkle_Sparkle.h:2:17:
     fatal error: jni.h: No such file or directory
compilation terminated.

**Comment by alpmestan** [comment]
Right, so when you're not using nix, you need to point GHC to where it can find JNI headers. On the Ubuntu VM I've been using, I simply installed openjdk (the jre and  jdk packages -- OpenJDK 7 or 8 should work, I've used both), the headers required were in `/usr/lib/jvm/java-8-openjdk-amd64/include` and `/usr/lib/jvm/java-8-openjdk-amd64/include/linux`. This means I had to issue the following command to get `sparkle` to build:

```sh
stack build --ghc-options "-I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux"
```

Let me know if that works for you as well.

**Comment by JulianZhang** [comment]
Dear, I had build success use the options as you said.

Thank you
