### ISSUE TITLE
Stack version mismatch causes build to fail

### ISSUE THREAD

**Issue by LucianU** [tweag/sparkle#147]
This image has nixpkgs pinned in nixpkgs.nix. The base image uses the nixpkgs-unstable channel. This means that the `stack` available in the container will be at the latest version, but the stack that nix calls in `shell.nix` here https://github.com/tweag/sparkle/blob/101ec44ebd826e4917fadb26e07c98079146af8c/shell.nix#L15 will be the one available in the pinned channel.

This version mismatch causes the build to fail.

**Comment by facundominguez** [comment]
#154 removes support for stack in favor of bazel.
