### ISSUE TITLE
How to make a Haskell type (record) available in Spark?

### ISSUE THREAD

**Issue by LucianU** [tweag/sparkle#148]
I have a type defined as
```haskell
data Session = Session { _appName :: Text, _bank :: Text }
```
and many other fields.

When using sparkle, I'm trying to decode the contents of a file to the type above. The code I use goes like this:

```haskell
rdd' <- textFile sc s3FileUri
decodedSessions <- RDD.map (closure (static (decodeStrict . encodeUtf8))) rdd'
```
For that to work, it seems I need to make my `Session` type available in Java land. How can I do that?

**Comment by facundominguez** [comment]
Hello, `RDD.map` has the following type:
```
map
  :: (Static (Reify a), Static (Reflect b), Typeable a, Typeable b)
  => Closure (a -> b)
  -> RDD a
  -> IO (RDD b)
```
Where `b` is instantiated to `Session`. Therefore, it requires an instance of [Static][https://github.com/tweag/distributed-closure/blob/793ee0627d8f7c62ab03de26abb62d1d363f1f54/src/Control/Distributed/Closure.hs#L61] `(Reflect Session)` which requires an instance of [Reflect][https://github.com/tweag/inline-java/blob/b63408726f07338656d73bb11e34cce3275b46c4/jvm/src/Language/Java.hs#L491] `Session`.

The utility of all this though, depends on what the input file format is and what you are going to compute with the resulting RDD.

**Comment by LucianU** [comment]
Unfortunately, I don't remember how I solved this, but since there is no general answer to the question, I think we can close the issue.
