### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by omefire** [tweag/sparkle#152]
Hello,

Commendable effort, that of making it possible to use Spark directly from Haskell programs.
Is the project still being maintained? Is there another project that you might recommend for interacting with Spark of Kafka?

Thanks,

**Comment by robinbb** [comment]
It is maintained, yes.

**Comment by robinbb** [comment]
@omefire Feel free to make contact with me to discuss your architectural requirements for your Spark/Kafka project.
