### ISSUE TITLE
Allow wrapping functions of arbitrary arity

### ISSUE THREAD

**Issue by alpmestan** [tweag/sparkle#16]
[At the moment](https://github.com/tweag/sparkle/blob/master/sparkle/src/Control/Distributed/Spark/Closure.hs), we only support functions of arity <= 4. This is most likely enough to cover all the Spark API but we might want to lift this limitation in the future when we start worrying about binding arbitrary Java APIs.

**Comment by mboes** [comment]
Closing as "won't fix". We can wrap functions of arbitrary arity - it's closures passed to Java that have max arity <= 4. However, the "4" limit doesn't come from Sparkle, but from Spark's Java API: http://spark.apache.org/docs/latest/api/java/org/apache/spark/api/java/function/package-summary.html. Java itself doesn't support anonymous functions before JDK 8, which we don't target yet.
