### ISSUE TITLE
Running on databricks

### ISSUE THREAD

**Issue by qfjp** [tweag/sparkle#161]
The readme mentions running on databricks, but the instructions are for an old build process. I've tried using the current method to generate a `jar` file and submit using [dbx](https://docs.databricks.com/dev-tools/dbx.html), but it looks like without the compiled libraries the runtime doesn't see the classes created from the haskell code. Is there still a way to use this without databricks or has that method been abandoned?

**Comment by facundominguez** [comment]
Hello! I don't have any recent experience with databricks. In my case, I have used sparkle with a cluster manually managed.

If the jar works when not deployed in databricks, it would be interesting to learn more details to understand the failure.

**Comment by qfjp** [comment]
The only real information I can give is the error message through dbx (this is just from the hello example):
```
NoClassDefFoundError: io/tweag/inlinejava/Inline__sparklelib_Control_Distributed_Spark_Context
Caused by: ClassNotFoundException: io.tweag.inlinejava.Inline__sparklelib_Control_Distributed_Spark_Context
at io.tweag.sparkle.SparkMain.invokeMain(Native Method)
	at io.tweag.sparkle.SparkMain.main(SparkMain.java:29)
```
which looks like databricks can't find any of the haskell code.

Running on my own computer, I can see that it definitely gets farther than this, though I still haven't set up everything spark/hadoop to verify an actual working example.

**Comment by facundominguez** [comment]
Those missing classes are generated by `inline-java` and fed to the JVM when calling `loadJavaWrappers` [here](https://github.com/tweag/sparkle/blob/master/src/Control/Distributed/Spark.hs#L60).

It could be that this code is not being invoked for some reason. One possibility is that if your test is using separate JVMs for the driver and the executors, the executors never call `loadJavaWrappers`. The README is suggesting [this fix](https://github.com/tweag/sparkle/#anonymous-classes-in-inline-java-quasiquotes-fail-to-deserialize), but I think I accidentally broke that advice last year by removing the necessary call to `loadJavaWrappers` in this commit: 4c289498. 

I would try reverting 4c289498, and adding 
```
diff --git a/apps/hello/HelloSpark.hs b/apps/hello/HelloSpark.hs
index 09bc034..cd01939 100644
--- a/apps/hello/HelloSpark.hs
+++ b/apps/hello/HelloSpark.hs
@@ -18,6 +18,8 @@ f2 s = "b" `Text.isInfixOf` s
 main :: IO ()
 main = forwardUnhandledExceptionsToSpark $ do
     conf <- newSparkConf "Hello sparkle!"
+    confSet conf "spark.serializer" "org.apache.spark.serializer.KryoSerializer"
+    confSet conf "spark.kryo.registrator" "io.tweag.sparkle.kryo.InlineJavaRegistrator"
     confSet conf "spark.hadoop.fs.s3a.aws.credentials.provider"
                  "org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider"
     sc   <- getOrCreateSparkContext conf
```

**Comment by facundominguez** [comment]
In #162 I'm trying a fix to have `loadJavaWrappers` called in executors. The "kryo.registrator" setup would still be necessary.

**Comment by qfjp** [comment]
It works! The "hello" example didn't actually print anything, but the "dataframe" one worked perfectly (minus the deprecated Library.Java functions). Thanks a lot, even if printing requires wrapping strings in a dataframe (or maybe an error, since I haven't tried) as a workaround

**Comment by qfjp** [comment]
Actually, stdout is viewable through the cluster logs, so no workarounds necessary

**Comment by facundominguez** [comment]
Glad to hear that it works! I'm closing this, but feel free to reach again if there are more issues.
