### ISSUE TITLE
Figure out why CircleCI needs -lpthread

### ISSUE THREAD

**Issue by alpmestan** [tweag/sparkle#22]
CircleCI reports a link error if examples are not built with -lpthread. We can't reproduce on any other machine.

Note from @mboes:

> One thing to note about the CI environment is that I switched it to using the gold linker, rather than the default ld.bfd, to work around other linker bugs. So maybe it's gold that introduced this particular bug (meaning there's no way to win...). So next step in this ticket is: test on later ubuntu with gold linker turned on. See circle.yml for how to turn on ld.gold.

**Comment by mboes** [comment]
Should be fixed by https://github.com/rrnewton/thread-local-storage/pull/6.

**Comment by mboes** [comment]
This issue has been fixed upstream.
