### ISSUE TITLE
AWS key for examples?

### ISSUE THREAD

**Issue by alanz** [tweag/sparkle#24]
The hello example fails with

```
16/03/17 09:52:51 INFO SparkContext: Created broadcast 0 from textFile at Sparkle.java:-2
Exception in thread "main" java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3 URL, or by setting the fs.s3.awsAccessKeyId or fs.s3.awsSecretAccessKey properties (respectively).	
```

Are there sample read-only AWS credentials for these? Or can they be made public?

**Comment by mboes** [comment]
Unfortunately, Spark doesn't know how to access S3 without any credentials. But creating example credentials with next to no capabilities is a good idea.

**Comment by mboes** [comment]
> Unfortunately, Spark doesn't know how to access S3 without any credentials.
Reference: http://stackoverflow.com/questions/31496152/access-public-available-amazon-s3-file-from-apache-spark

**Comment by alpmestan** [comment]
@alanz Hi! You should now be able to run the examples, if you pull the commit I just pushed (ea3fb6728c6f67b4c5a4bd6967dea71fc862c17b). Can you confirm it now works for you as well?

**Comment by alanz** [comment]
Yes it does, thanks.

```
20 lines with a, 20 lines with b.
```
