### ISSUE TITLE
Add missing callXXXMethod functions

### ISSUE THREAD

**Issue by alpmestan** [tweag/sparkle#32]
We're currently missing a few variants of the JNI `callXXX` functions. Namely:

- `callFloatMethod`
- `callStaticBooleanMethod`
- `callStaticByteMethod`
- `callStaticCharMethod`
- `callStaticShortMethod`
- `callStaticIntMethod`
- `callStaticLongMethod`
- `callStaticFloatMethod`
- `callStaticDoubleMethod`

Once we have those, we should also not forget to add support for them in the generic `call`/`callStatic` functions.

**Comment by mboes** [comment]
Idea for implementation: these are all defined pretty similarly so the code is very repetitive. It would likely be less error prone to introduce TH macros to write these functions more succinctly. Same thing for the get/set/release primitive arrays functions.
