### ISSUE TITLE
Current Hackage version misses io_tweag_sparkle_Sparkle.h

### ISSUE THREAD

**Issue by mgajda** [tweag/sparkle#39]
Seems that the package version currently on Hackage is missing a critical file, and thus is unable to compile straight from Hackage:
```
[12 of 12] Compiling Control.Distributed.Spark ( src/Control/Distributed/Spark.hs, dist/build/Control/Distributed/Spark.o )

cbits/bootstrap.c:4:38:
     fatal error: io_tweag_sparkle_Sparkle.h: No such file or directory
compilation terminated.
```

Could it be that the package is missing and extra line in `extra-source-files` or `extra-c-source-files`?

**Comment by mboes** [comment]
New release pushed to Hackage. Thanks for the report!
