### ISSUE TITLE
Test validity of built package in CI

### ISSUE THREAD

**Issue by mgajda** [tweag/sparkle#40]
It seems that at least one previously reported issue has stemmed from the fact that CircleCI configuration does _not_ test for validity of the built package.

I do not use CircleCI yet, so it would take a little bit more work for me to submit a patch, but here is how I do it on Travis CI:

``` yaml
  # tests that a source-distribution can be generated
  - cabal-$CABALVER sdist
  - echo "Package distribution built."

  # check that the generated source-distribution can be built & installed
  - export SRC_TGZ=$(cabal-$CABALVER info . | awk '{print $2 ".tar.gz";exit}') ;
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
       cabal-$CABALVER sandbox init
       cabal-$CABALVER install "$SRC_TGZ";
    else
       echo "expected '$SRC_TGZ' not found";
       exit 1;
    fi  
  - echo "Package built successfully!"
```

**Comment by mboes** [comment]
Good idea. If at all possible though it would be nice if we only had to build once.

**Comment by facundominguez** [comment]
Closing this as #154 removes support for stack/cabal in favor of bazel.
