### ISSUE TITLE
Readme EC2 scripts link broken

### ISSUE THREAD

**Issue by nh2** [tweag/sparkle#46]
In the Readme, section

> See here for other options, including lauching a whole cluster from scratch on EC2.

the "lauching a whole cluster from scratch on EC2." link is broken for `/latest/`; `/1.2.1/` has it, but maybe the latest scripts are now somewhere else?

**Comment by mboes** [comment]
Thanks. Looks like Apache Spark removed the EC2 scripts in version 2.0, and `/latest/` now points to 2.0. So I now point to 1.6.2, the latest non-2.0 release.
