### ISSUE TITLE
The README doesn't explain how sparkle works

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tweag/sparkle#52]
I think the README, at the very start, should explain *how* sparkle works.

It makes it possible to build a jar file that is executed on spark, but how is this done?  Is haskell code compiled to javascript, interpreted through an intercal implementation of javascript in the JVM?  Is it compiled to native code called through JNI?

How does it work?  A paragraph or a few lines would help a lot.

**Comment by mboes** [comment]
I think the first thing a user wants to see is *what* Sparkle can do for her/him, not *how* it does it. Though an explanation of how things work under the hood would certainly be useful in a later section / separate page. We currently say that Sparkle is a library for doing distributed computing using Spark under the hood. And point to [this blog post](https://tweag-blog.herokuapp.com/posts/2016-02-25-hello-sparkle.html) for the full version. As explained there, it calls native code via JNI. Perhaps propose to a PR that cribs the info that you'd want to see?

**Comment by alexanderkjeldaas** [comment]
Thanks.  Great fix. :-)
