### ISSUE TITLE
Spark 2 support

### ISSUE THREAD

**Issue by mboes** [tweag/sparkle#55]
sparkle currently only supports Spark 1.6. But [Spark](http://spark.apache.org/downloads.html) has since moved on. Latest is 2.0.1 at time of writing.

**Comment by robinbb** [comment]
Latest is now 2.1.0. There is a 2.0.2 version, also.

**Comment by facundominguez** [comment]
A provisional PR to leapyear-patchset
https://github.com/LeapYear/leapyear-sparkle/pull/6
I'm still preparing the patch for upstream.

**Comment by mboes** [comment]
Has the required changes for the support been merged in this repository?

**Comment by robinbb** [comment]
Sorry, @mboes. Closed the wrong issue. My bad. Thanks for checking.

**Comment by mboes** [comment]
Ok no worries. :)

**Comment by facundominguez** [comment]
nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/22505
Some of the needed changes to sparkle live in a private repo for now. They are not ready for a PR in tweag/sparkle until the nixpkgs PR is merged.

**Comment by robinbb** [comment]
The above PR is merged, now, FYI.

**Comment by mboes** [comment]
This has been fixed in master since a long time ago.
