### ISSUE TITLE
Document threading requirements

### ISSUE THREAD

**Issue by facundominguez** [tweag/sparkle#72]
While trying to write some tests of sparkle using `tasty` I found that it doesn't seem to work when bound threads other than the main one are used. The following program fails with:
```
$ stack --nix exec -- spark-submit --master 'local[1]' sparkle-example-osthreads.jar
16/12/19 10:30:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/12/19 10:30:29 WARN Utils: Your hostname, fd-tweag resolves to a loopback address: 127.0.0.1; using 192.168.1.44 instead (on interface wlan0)
16/12/19 10:30:29 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Exception in thread "Thread-28" java.lang.NoClassDefFoundError: io/tweag/sparkle/function/HaskellFunction2
Caused by: java.lang.ClassNotFoundException: io.tweag.sparkle.function.HaskellFunction2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
sparkle-worker: JavaException (J 0x00002af520002aa8)
```

but it succeeds if `runOS` is replaced with `id`:
```
$ stack --nix exec -- sparkle package sparkle-example-osthreads
facundo@fd-tweag:~/tweag/leapyear/leapyear-server/leapyear-algorithms/sparkle$ stack --nix exec -- spark-submit --master 'local[1]' sparkle-example-osthreads.jar
16/12/19 10:31:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/12/19 10:31:19 WARN Utils: Your hostname, fd-tweag resolves to a loopback address: 127.0.0.1; using 192.168.1.44 instead (on interface wlan0)
16/12/19 10:31:19 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
total sum: 55.0
```

```Haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StaticPointers #-}

module Main where

import Control.Concurrent
import Control.Exception
import Control.Distributed.Closure
import Control.Distributed.Spark as RDD


runOS :: forall a. IO a -> IO a
runOS m = do
    mv <- newEmptyMVar :: IO (MVar (Either SomeException a))
    forkOS (try m >>= putMVar mv)
    takeMVar mv >>= either throw return

main :: IO ()
main = do
    conf <- newSparkConf "osthreads sparkle"
    sc   <- getOrCreateSparkContext conf
    rdd  <- runOS $ RDD.parallelize sc [1..10:: Double]
    d  <- runOS $ RDD.reduce (closure $ static (+)) rdd
    putStrLn $ "total sum: " ++ show d
```

This request may concern the packages `jvm` and `jni` in the dependencies. The main questions that documentation should make clear are: what threads can make sparkle calls? How can references to values created by the different threads be shared?

I've tried binding `NewGlobalRef` and create global references to `rdd` and `sc`, but the program still fails with similar exceptions.

Only making all calls in the main thread seems to succeed. If only one OS thread is created to run all the calls, the program fails as above also.

The example can be found in https://github.com/LeapYear/sparkle/commit/be533feec4b97c18e8d14dc60aa6ff91bd826e38.
cc @alpmestan, @robinbb

**Comment by mboes** [comment]
The requirements on threads are pretty straightforward: functions defined in the `jni` package can only be called from bound threads. This is the same requirement as for OpenGL, which `base` uses as an example to explain why bound threads are necessary. Like the documentation for `base` explains, bound threads are necessary for any call to any library that makes use of thread local storage. The fact that `jni` uses thread local storage is documented at the very top of the `Foreign.JNI` module. We could remind users from somewhere central that sparkle uses `jni` under the hood, therefore sparkle functions inherit the same constraints.

The reason why calling from `main` works while calling from other threads does not is because `main` is always bound. This is also documented in `base`: http://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Concurrent.html#g:8.

**Comment by facundominguez** [comment]
@mboes, with that statement, I would expect sparkle to work from any thread created with `forkOS`, but it is doesn't currently.

**Comment by mboes** [comment]
Are you reusing the Spark context in the `forkOS`'ed thread?

**Comment by facundominguez** [comment]
This is the failing test:
```
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StaticPointers #-}
module Main where

import Control.Concurrent
import Control.Exception
import Control.Distributed.Closure
import Control.Distributed.Spark as RDD


runOS :: forall a. IO a -> IO a
runOS m = do
    mv <- newEmptyMVar :: IO (MVar (Either SomeException a))
    forkOS (try m >>= putMVar mv)
    takeMVar mv >>= either throw return

main :: IO ()
main = runOS $ do
    conf <- newSparkConf "osthreads sparkle"
    sc   <- getOrCreateSparkContext conf
    rdd  <- RDD.parallelize sc [1..10:: Double]
    d  <- RDD.reduce (closure $ static (+)) rdd
    putStrLn $ "total sum: " ++ show d
```
It is shared here https://github.com/LeapYear/sparkle/commit/be533feec4b97c18e8d14dc60aa6ff91bd826e38

**Comment by facundominguez** [comment]
Here is an example that creates the SparkContext on the main thread and then makes it a global reference:
https://github.com/LeapYear/sparkle/blob/fd/osthreads2/apps/osthreads/osthreads.hs

It fails the same.

**Comment by facundominguez** [comment]
This is what the problem looks like:
https://developer.android.com/training/articles/perf-jni.html#faq_FindClass

Note that the documentation of [FindClass](http://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#FindClass) mentions the property java.class.path. This suggested the following workaround which makes the last program succeed:
```
stack --nix exec -- spark-submit --master 'local[1]' --driver-java-options -Djava.class.path=/home/facundo/tweag/leapyear/leapyear-server/leapyear-algorithms/sparkle/sparkle-example-osthreads.jar:/nix/store/9s0arikf42nc92jk22095dfzchsp2whs-spark-1.6.0-bin-cdh4.tgz/lib/spark-assembly-1.6.0-hadoop2.0.0-mr1-cdh4.2.0.jar:. sparkle-example-osthreads.jar
...
total sum: 55.0
```

**Comment by robinbb** [comment]
@facundominguez @mboes Does this last comment mean that JNI calls can be made from any thread, not merely the bound thread, provided the JVM is given the appropriate setting for java.class.path?

**Comment by facundominguez** [comment]
Only bound threads may be used.

**Comment by facundominguez** [comment]
Today, I managed to make sparkle calls from a different thread without fiddling with the classpath.

Firstly, JNI's `FindClass` can't find spark classes, but the context ClassLoader of the thread calling into Haskell can via the `loadClass` method. This requires changing the package `jni` so we can set the class loader to use for JNI calls. Also, note that unlike `FindClass`, `loadClass` expects names to have dots "java.lang.String" rather than slashes "java/lang/String".

Secondly, spark, sometimes expects the context ClassLoader of the current thread to be able to load spark classes. Therefore, in addition to attaching the OS thread to the running jvm, the context ClassLoader of the thread needs to be set with the context ClassLoader of the thread which called into haskell.

And that seems to be all folks!

**Comment by facundominguez** [comment]
After some more thought, I think the following could work the best. We leave the `jni` package unmodified. The user is still free to use `findClass :: String -> IO JClass` with the meaning that the JNI interface gives to it.

Instead, we have the `jvm` package use a function `loadClass :: String -> IO JClass` provided by the user. When the user doesn't specify a function, the default behavior is to use `findClass` from the package `jni`.

The package `sparkle`, in turn, sets a function `loadClass` which uses the context ClassLoader.

To set the context ClassLoader in newly attached threads, we could have the package `jni` provide hooks that can be run whenever a thread is attached. `sparkle` can then set a hook for this sake.

**Comment by facundominguez** [comment]
The method `java.lang.ClassLoader.loadClass` didn't work for arrays. `Class.forName` seems to do it though.

**Comment by facundominguez** [comment]
Documented in #154.
