### ISSUE TITLE
Make newtype wrappers of Java references convenient to use.

### ISSUE THREAD

**Issue by facundominguez** [tweag/sparkle#93]
Consider the [newtype Row](https://github.com/tweag/sparkle/blob/007caf43bde71d6cfa49168af502486d365fe0d2/src/Control/Distributed/Spark/SQL/Row.hs#L18).
```Haskell
newtype Row = Row (J ('Class "org.apache.spark.sql.Row"))
instance Coercible Row ('Class "org.apache.spark.sql.Row")
```
It doesn't have Reify/Reflect instances. Therefore, it has to be used in conjunction with `Data.Coerce.coerce` in [tests](https://github.com/tweag/sparkle/blob/007caf43bde71d6cfa49168af502486d365fe0d2/apps/dataframe/Main.hs#L91-L98).
```Haskell
select df1 [arrCols]
  >>= javaRDD
  >>= \rdd -> collect
        (Data.Coerce.coerce rdd
           :: RDD (J ('Class "org.apache.spark.sql.Row")))
  >>= mapM (getList 0 . Data.Coerce.coerce)
  >>= mapM (mapM (\x -> (reify (unsafeCast x) :: IO Double)))
  >>= print
```
While if it had Reify/Reflect instances one could simply write:
```Haskell
select df1 [arrCols]
  >>= javaRDD
  >>= collect
  >>= mapM (getList 0)
  >>= mapM (mapM (\x -> (reify (unsafeCast x) :: IO Double)))
  >>= print
```

The documentation of the type class `Reify` says that it extracts a concrete Haskell value. When introducing the bindings it was argued that newtype wrappers around Java references shouldn't have Reify instances. Does "concrete Haskell value" mean that all of a data structure needs to be allocated in the Haskell heap?

In principle for every data structure, one could choose to have it completely in Haskell, completely in Java or mixed between the two sides. It would make sense for the sparkle bindings to streamline all three cases instead of only the first one.

**Comment by facundominguez** [comment]
cc @alpmestan

**Comment by alpmestan** [comment]
For the particular case of `Row`, when dealing with conversions betweens `Dataframe` and `RDD Row`, this is indeed quite inconvenient. Say we want to extract some Haskell data type from a `Row`. If we have an RDD of `Row`s, and we want to `map` a `(Row -> SomeType)` function over it. Well, IIRC, we can `reify`/`reflect` functions of an argument when the argument and result types are themselves `Reify`able and `Reflect`able, right? If that's indeed true, it effectively means that we exclude functions `Row -> a` and `a -> Row`, which are perfectly sensible and even useful in real applications, forcing us to use `J ('Class ...)` instead of `Row` and `coerce` everywhere.

**Comment by mboes** [comment]
This sounds like a `jvm` issue more than a `sparkle` one.

Do you have a proposal to improve the situation? One option I see could be to modify `Reify`/`Reflect` to look as follows:

```haskell
class (Interp (Uncurry a) ~ ty, SingI ty, IsReferenceType ty) => Reify a ty where
  reify :: Data.Coerce.Coercible b (J ty) => b -> IO a

class (Interp (Uncurry a) ~ ty, SingI ty, IsReferenceType ty) => Reflect a ty where
  reflect :: Data.Coerce.Coercible (J ty) b => a -> IO b
```

But I'm concerned about the potential for ambiguity and the quality of type errors. Thoughts?

At any rate, we should add

```haskell
jobject :: (Coercible a ty, IsReferenceType ty) => a -> J ty
jobject x = case coerce x of JObject y -> y; _ -> error "impossible" 
```

to `jvm`. This alone would already make your code snippet a lot nicer.

**Comment by facundominguez** [comment]
> This alone would already make your code snippet a lot nicer.

It improves indeed:
```
select df1 [arrCols]
  >>= javaRDD
  >>= RDD.map jobject
  >>= collect
  >>= mapM (getList 0 . Data.Coerce.coerce)
  >>= mapM (mapM (\x -> (reify (unsafeCast x) :: IO Double)))
  >>= print
```

I fail to see how the following changes would help.
```
...
  reify :: Data.Coerce.Coercible b (J ty) => b -> IO a
...
  reflect :: Data.Coerce.Coercible (J ty) b => a -> IO b
```
If the Reify/Reflect instances are not available, modifying the classes doesn't solve it.

Perhaps it would be useful if sparkle offered some way to access the local java references in an RDD without forcing usage of Reify and Reflect. These mechanism could then be used to implement the bindings which do use reify and reflect. After all, all the snippets in this issue are creating global java references unnecessarily.

**Comment by mboes** [comment]
@facundominguez Github autoclosed this ticket. Do reopen it though if the kit in tweag/inline-java#63 doesn't completely solve the original use case.

**Comment by facundominguez** [comment]
It's fine. Continuing the discussion on providing access to the local java references would deserve a separate issue.

**Comment by mboes** [comment]
Agreed. Go ahead write up what you have in mind.
